version: '3.8'

services:
  rpc-proxy:
    build:
      context: ./nginx-proxy
    ports:
      - "8080:8080"
    networks:
      - rpc-network
    depends_on:
      - health-checker
    volumes:
      - ./secrets/default_providers.json:/usr/local/openresty/nginx/providers.json
      - ./secrets/.htpasswd:/etc/nginx/.htpasswd
    environment:
      CONFIG_HEALTH_CHECKER_URL: http://health-checker:8080/providers
      CUSTOM_DNS: 127.0.0.11
      RELOAD_INTERVAL: "10"

  health-checker:
    build:
      context: rpc-health-checker
    ports:
      - "8081:8080"
    networks:
      - rpc-network
    volumes:
      - ./secrets:/config
    environment:
      DEFAULT_PROVIDERS_PATH: /config/default_providers.json
      REFERENCE_PROVIDERS_PATH: /config/reference_providers.json
      PORT: "8080"

networks:
  rpc-network:
    driver: bridge
