version: '3.8'

services:
  rpc-proxy:
    build:
      context: ./nginx-proxy
    ports:
      - "8080:8080"
    networks:
      - rpc-network
    depends_on:
      - health-checker
    volumes:
      - ./secrets/default_providers.json:/usr/local/openresty/nginx/providers.json
      - ./secrets/.htpasswd:/etc/nginx/.htpasswd
    environment:
      CONFIG_HEALTH_CHECKER_URL: http://health-checker:8080/providers
      CUSTOM_DNS: 127.0.0.11
      RELOAD_INTERVAL: "10"

  health-checker:
    build:
      context: rpc-health-checker
    ports:
      - "8081:8080"
    networks:
      - rpc-network
    volumes:
      - ./secrets:/config
    environment:
      DEFAULT_PROVIDERS_PATH: /config/default_providers.json
      REFERENCE_PROVIDERS_PATH: /config/reference_providers.json
      PORT: "8080"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - rpc-network
    depends_on:
      - health-checker

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - rpc-network
    depends_on:
      - prometheus

volumes:
  grafana-storage:

networks:
  rpc-network:
    driver: bridge
