services:
  test-api:
    build:
      context: './test-api'
      dockerfile: Dockerfile
    container_name: 'test-api'
    restart: 'always'
    ports:
      - '3001:3000'
    networks:
      - 'rpc-network'
    environment:
      - REACT_APP_RPC_PROXY_URL=http://localhost:8080
    depends_on:
      - 'rpc-proxy'
      - 'auth-service'

  rpc-proxy:
    build:
      context: './nginx-proxy'
      dockerfile: Dockerfile.local
    container_name: 'rpc-proxy'
    restart: 'always'
    environment:
      CONFIG_HEALTH_CHECKER_URL: 'http://health-checker:8082/providers'
      GO_AUTH_SERVICE_URL: 'http://auth-service:8081'
      CUSTOM_DNS: '127.0.0.11'
      RELOAD_INTERVAL: '10'
      AUTH_CONFIG_FILE: '/app/auth_config.json'
      CACHE_RULES_FILE: '/app/cache_rules.yaml'
      KEYDB_CONFIG_FILE: '/app/keydb_config.yaml'
      CORS_ORIGIN: 'http://localhost:3001'
      KEYDB_URL: 'redis://keydb:6379'
    ports:
      - '8080:8080'
    networks:
      - 'rpc-network'
    depends_on:
      - 'health-checker'
      - 'auth-service'
    volumes:
      - './secrets/default_providers.json:/app/providers.json:ro'
      - './secrets/.htpasswd:/etc/nginx/.htpasswd:ro'
      - './go-auth-service/auth_config.json:/app/auth_config.json:ro'
      - './nginx-proxy/cache_rules.yaml:/app/cache_rules.yaml:ro'
      - './nginx-proxy/keydb_config.yaml:/app/keydb_config.yaml:ro'

  auth-service:
    build:
      context: './go-auth-service'
      dockerfile: Dockerfile
    container_name: 'auth-service'
    restart: 'always'
    environment:
      CONFIG_FILE: '/app/config.json'
      PORT: '8081'
    ports:
      - '8081:8081'
    networks:
      - 'rpc-network'
    volumes:
      - './go-auth-service/auth_config.json:/app/config.json:ro'

  health-checker:
    build:
      context: './rpc-health-checker'
    container_name: 'health-checker'
    restart: 'always'
    environment:
      DEFAULT_PROVIDERS_PATH: '/config/default_providers.json'
      REFERENCE_PROVIDERS_PATH: '/config/reference_providers.json'
      PORT: '8082'
    ports:
      - '8082:8082'
    networks:
      - 'rpc-network'
    volumes:
      - './secrets:/config:ro'

  rpc-proxy-metrics:
    image: 'nginx/nginx-prometheus-exporter:1.4'
    container_name: 'rpc-proxy-metrics'
    restart: 'always'
    command: 
      - '--nginx.scrape-uri=http://rpc-proxy:8080/stub_status'
      - '--web.listen-address=:8090'
    ports:
      - '8090:8090'
    networks:
      - 'rpc-network'

  keydb:
    image: 'eqalpha/keydb:latest'
    container_name: 'keydb'
    restart: 'always'
    ports:
      - '6379:6379'
    networks:
      - 'rpc-network'
    command: 
      - 'keydb-server'
      - '--protected-mode'
      - 'no'
      - '--appendonly'
      - 'yes'
    healthcheck:
      test: ['CMD', 'keydb-cli', 'ping']
      interval: '30s'
      timeout: '10s'
      retries: 3
      start_period: '10s'
    volumes:
      - 'keydb-data:/data'

  keydb-exporter:
    image: 'oliver006/redis_exporter:v1.74.0'
    container_name: 'keydb-exporter'
    restart: 'always'
    ports:
      - '9121:9121'
    networks:
      - 'rpc-network'
    environment:
      REDIS_ADDR: 'keydb:6379'
    depends_on:
      - 'keydb'

  prometheus:
    image: 'prom/prometheus:latest'
    container_name: 'prometheus'
    restart: 'always'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - 'rpc-network'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    depends_on:
      - 'health-checker'
      - 'auth-service'

  grafana:
    image: 'grafana/grafana:latest'
    container_name: 'grafana'
    restart: 'always'
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    networks:
      - 'rpc-network'
    volumes:
      - 'grafana-storage:/var/lib/grafana'
      - './grafana/provisioning/datasources:/etc/grafana/provisioning/datasources'
      - './grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards'
    depends_on:
      - 'prometheus'

volumes:
  grafana-storage:
  keydb-data:

networks:
  rpc-network:
    driver: bridge
