global:
  scrape_interval: 15s

rule_files:
  - "prometheus-alerts.yml"

scrape_configs:
  - job_name: 'health-checker'
    static_configs:
      - targets: ['health-checker:8082']

  - job_name: 'rpc-proxy-metrics'
    static_configs:
      - targets: ['rpc-proxy-metrics:8090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'nginx-cache-metrics'
    static_configs:
      - targets: ['rpc-proxy:8080']
    scrape_interval: 30s
    metrics_path: '/metrics/cache'
    scheme: http

  - job_name: 'cache-service'
    static_configs:
      - targets: ['cache-service:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: http
