global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'health-checker'
    static_configs:
      - targets: ['health-checker:8080']

  - job_name: 'rpc-proxy-metrics'
    static_configs:
      - targets: ['rpc-proxy-metrics:8090']
