// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=cache.go -destination=mock/cache.go
//

// Package mock is a generated GoMock package.
package mock

import (
	models "go-proxy-cache/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCache) Delete(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", key)
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCache)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockCache) Get(key string) (*models.CacheEntry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*models.CacheEntry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), key)
}

// GetStale mocks base method.
func (m *MockCache) GetStale(key string) (*models.CacheEntry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStale", key)
	ret0, _ := ret[0].(*models.CacheEntry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetStale indicates an expected call of GetStale.
func (mr *MockCacheMockRecorder) GetStale(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStale", reflect.TypeOf((*MockCache)(nil).GetStale), key)
}

// Set mocks base method.
func (m *MockCache) Set(key string, val []byte, ttl models.TTL) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, val, ttl)
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(key, val, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), key, val, ttl)
}

// MockLevelAwareCache is a mock of LevelAwareCache interface.
type MockLevelAwareCache struct {
	ctrl     *gomock.Controller
	recorder *MockLevelAwareCacheMockRecorder
}

// MockLevelAwareCacheMockRecorder is the mock recorder for MockLevelAwareCache.
type MockLevelAwareCacheMockRecorder struct {
	mock *MockLevelAwareCache
}

// NewMockLevelAwareCache creates a new mock instance.
func NewMockLevelAwareCache(ctrl *gomock.Controller) *MockLevelAwareCache {
	mock := &MockLevelAwareCache{ctrl: ctrl}
	mock.recorder = &MockLevelAwareCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLevelAwareCache) EXPECT() *MockLevelAwareCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLevelAwareCache) Delete(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", key)
}

// Delete indicates an expected call of Delete.
func (mr *MockLevelAwareCacheMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLevelAwareCache)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockLevelAwareCache) Get(key string) (*models.CacheEntry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*models.CacheEntry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLevelAwareCacheMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLevelAwareCache)(nil).Get), key)
}

// GetStale mocks base method.
func (m *MockLevelAwareCache) GetStale(key string) (*models.CacheEntry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStale", key)
	ret0, _ := ret[0].(*models.CacheEntry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetStale indicates an expected call of GetStale.
func (mr *MockLevelAwareCacheMockRecorder) GetStale(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStale", reflect.TypeOf((*MockLevelAwareCache)(nil).GetStale), key)
}

// GetStaleWithLevel mocks base method.
func (m *MockLevelAwareCache) GetStaleWithLevel(key string) *models.CacheResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaleWithLevel", key)
	ret0, _ := ret[0].(*models.CacheResult)
	return ret0
}

// GetStaleWithLevel indicates an expected call of GetStaleWithLevel.
func (mr *MockLevelAwareCacheMockRecorder) GetStaleWithLevel(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaleWithLevel", reflect.TypeOf((*MockLevelAwareCache)(nil).GetStaleWithLevel), key)
}

// GetWithLevel mocks base method.
func (m *MockLevelAwareCache) GetWithLevel(key string) *models.CacheResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithLevel", key)
	ret0, _ := ret[0].(*models.CacheResult)
	return ret0
}

// GetWithLevel indicates an expected call of GetWithLevel.
func (mr *MockLevelAwareCacheMockRecorder) GetWithLevel(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithLevel", reflect.TypeOf((*MockLevelAwareCache)(nil).GetWithLevel), key)
}

// Set mocks base method.
func (m *MockLevelAwareCache) Set(key string, val []byte, ttl models.TTL) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, val, ttl)
}

// Set indicates an expected call of Set.
func (mr *MockLevelAwareCacheMockRecorder) Set(key, val, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockLevelAwareCache)(nil).Set), key, val, ttl)
}
