// Code generated by MockGen. DO NOT EDIT.
// Source: jsonrpc.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=jsonrpc.go -destination=mock/jsonrpc.go
//

// Package mock is a generated GoMock package.
package mock
